[[category]]
    name = 'Sample'
    problems = [
        'aplusb'
    ]

[[category]]
    name = 'Data Structure'
    problems = [
        'unionfind',
        'staticrmq',
    ]

[[category]]
    name = 'Graph'
    problems = [
        'lca',
        'scc',
        'bipartitematching',
        'assignment',
        'directedmst',
        'dominatortree',
    ]

[[category]]
    name = 'Math'
    problems = [
        'factorize',
        'convolution_mod',
        'multipoint_evaluation',
        'polynomial_interpolation',
        'exp_of_formal_power_series',
        'partition_function',
        'sum_of_floor_of_linear',
        'sqrt_mod',
        'two_sat',
    ]

[[category]]
    name = 'Matrix'
    problems = [
        'matrix_det',
        'sparse_matrix_det',
    ]

[[category]]
    name = 'String'
    problems = [
        'zalgorithm',
        'suffixarray',
        'runenumerate',
    ]
