[[category]]
    name = 'Sample'
    problems = [
        'aplusb'
    ]

[[category]]
    name = 'Data Structure'
    problems = [
        'unionfind',
        'staticrmq',
        'point_add_range_sum',
        'vertex_add_path_sum',
        'vertex_add_subtree_sum',
        'rectangle_sum',
    ]

[[category]]
    name = 'Graph'
    problems = [
        'lca',
        'scc',
        'bipartitematching',
        'general_matching',
        'assignment',
        'directedmst',
        'manhattanmst',
        'dominatortree',
        'maximum_independent_set'
    ]

[[category]]
    name = 'Math'
    problems = [
        'factorize',
        'convolution_mod',
        'multipoint_evaluation',
        'polynomial_interpolation',
        'inv_of_formal_power_series',
        'exp_of_formal_power_series',
        'log_of_formal_power_series',
        'sqrt_of_formal_power_series',
        'bernoulli_number',
        'partition_function',
        'sum_of_floor_of_linear',
        'sqrt_mod',
        'kth_root_integer',
        'discrete_logarithm_mod',
        'two_sat',
    ]

[[category]]
    name = 'Matrix'
    problems = [
        'matrix_det',
        'sparse_matrix_det',
        'system_of_linear_equations',
    ]

[[category]]
    name = 'String'
    problems = [
        'zalgorithm',
        'suffixarray',
        'number_of_substrings',
        'runenumerate',
    ]
