[[category]]
    name = 'Sample'
    problems = [
        'aplusb'
    ]

[[category]]
    name = 'Data Structure'
    problems = [
        'unionfind',
        'staticrmq',
    ]

[[category]]
    name = 'Graph'
    problems = [
        'lca',
    ]

[[category]]
    name = 'Math'
    problems = [
        'convolution_mod',
        'matrix_det',
        'sparse_matrix_det',
    ]

[[category]]
    name = 'String'
    problems = [
        'zalgorithm',
        'suffixarray',
        'runenumerate',
    ]
