[[category]]
    name = 'Sample'
    problems = [
        'aplusb'
    ]

[[category]]
    name = 'Data Structure'
    problems = [
        'unionfind',
        'staticrmq',
    ]

[[category]]
    name = 'Graph'
    problems = [
        'lca',
        'scc',
        'bipartitematching',
        'assignment',
    ]

[[category]]
    name = 'Math'
    problems = [
        'factorize',
        'convolution_mod',
        'matrix_det',
        'sparse_matrix_det',
        'multipoint_evaluation',
        'sum_of_floor_of_linear',
    ]

[[category]]
    name = 'String'
    problems = [
        'zalgorithm',
        'suffixarray',
        'runenumerate',
    ]
