name: CI

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: yosupo06/library-checker-judge
          path: library-checker-judge
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install
        run: |
          npm ci
      - name: gen protoc
        run: |
          ./gen_protoc.sh library-checker-judge/api/proto/library_checker.proto
      - name: prettier:check
        run: |
          npm run prettier:check
      - name: lint
        run: |
          npm run lint
      - name: build
        run: |
          npm run build
