name: CI

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: install
        run: |
          npm install
      - name: lint-test
        run: |
          npm run lint-test
      - name: lint
        run: |
          npm run lint
