name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: yosupo06/library-checker-judge
          path: library-checker-judge
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Run npm ci
        run: |
          npm ci
      - name: Generate protoc
        run: npm run protoc
        env:
          PROTO_PATH: ./library-checker-judge/api/proto
      - name: Test
        run: npm run coverage
      - name: Prettier
        run: npm run prettier:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
