name: CI

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm run lint
