name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      problems-branch:
        type: string
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        description: environment of deploy
      judge-branch:
        type: string
        default: master
        description: branch of library-checker-judge

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: yosupo06/library-checker-judge
          path: library-checker-judge
          ref: ${{ inputs.judge-branch }}

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
          service_account: app-engine-deployer@library-checker-project.iam.gserviceaccount.com
          token_format: access_token

      - name: Run npm ci
        run: npm ci

      - name: Generate protoc
        run: npx protoc --ts_out src/api/ --proto_path ./library-checker-judge/api/proto ./library-checker-judge/api/proto/library_checker.proto

      - name: Run npm build
        run: npm run build -- --mode ${{ (inputs.env == 'prod' && 'production') || 'staging' }}

      - name: Deploy app.yaml
        run: gcloud app deploy --quiet app-${{ inputs.env }}.yaml

      - name: Deploy dispatch.yaml
        run: gcloud app deploy --quiet dispatch.yaml
