name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      judge-branch:
        type: string
        default: master
  workflow_dispatch:
    inputs:
      env:
        type: string
        default: dev
        description: environment of deploy
      judge-branch:
        type: string
        default: master
        description: branch of library-checker-judge

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: yosupo06/library-checker-judge
          path: library-checker-judge
          ref: ${{ inputs.judge-branch }}

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
        working-directory: ./terraform
      - id: tf-output
        run: terraform output --json
        working-directory: ./terraform
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ fromJson(steps.tf-output.outputs.stdout).gh_provider_id.value }}
          service_account: ${{ fromJson(steps.tf-output.outputs.stdout).frontend_sa_email.value }}
          token_format: access_token

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - run: npm ci
      - run: npm install -g firebase-tools

      - run: npm run protoc
        env:
          PROTO_PATH: ./library-checker-judge/api/proto
      - run: npm run build -- --mode ${{ (inputs.env == 'prod' && 'production') || 'staging' }}

      - run: firebase use ${{ inputs.env }}
      - run: firebase deploy
